params_xgb:
  objective: 'multi:softprob'
  eval_metric: 'mlogloss'
  num_class: 9
  max_depth: 12
  eta: 0.1
  min_child_weight: 10
  subsample: 0.9
  colsample_bytree: 0.8
  silent: 1
  random_state: 71
  num_round: 350
  early_stopping_rounds: 10

params_nn:
  layers: 3
  nb_epoch: 5 # 1000 # サンプルのため早く終わるように設定
  patience: 10
  dropout: 0.5
  units: 512